case_args:
  normalizer: 'Gaussian'
  normalizer_path: 'trained_preprocessors/preprocessor_gaussian_32x32_Pressure.pkl'



data_args:
  file_path: '/samoa/data/smrserraoseabr/subsurface-DA-with-generative-models/data/32x32'
  num_samples: 1000


dataloader_args:
  batch_size: 10
  num_workers: 4
  shuffle: True

model_args:
  num_dense_neurons: [64, 128]
  num_channels: [32, 64, 128, 256] #[128, 64, 32, 16, 8]
  activation: 'gelu'
  num_output_channels: 1
  grid_resolution: 32

  
optimizer_args:
  learning_rate: 1.0e-4
  weight_decay: 1.0e-6
  scheduler_args:
    type: 'cosine'
    args:
      T_max: 5000
      #patience: 100
      #factor: 0.9
      #min_lr: 1.0e-6
      #warmup: 25
      #total_steps: 2000

train_stepper_args:

trainer_args:
  num_epochs: 500
