case_args:
  normalizer: Gaussian
  normalizer_path: trained_preprocessors/preprocessor_gaussian_32x32_Pressure.pkl
data_args:
  file_path: /samoa/data/smrserraoseabr/subsurface-DA-with-generative-models/data/32x32
  num_samples: 1000
dataloader_args:
  batch_size: 10
  num_workers: 4
  shuffle: true
model_args:
  activation: gelu
  grid_resolution: 32
  num_channels:
  - 32
  - 64
  - 128
  - 256
  num_dense_neurons:
  - 64
  - 128
  num_output_channels: 1
optimizer_args:
  learning_rate: 0.0001
  scheduler_args:
    args:
      T_max: 5000
    type: cosine
  weight_decay: 1.0e-06
train_stepper_args: null
trainer_args:
  num_epochs: 500
